### ISSUE TITLE
Can not load DBert-ft  model

### ISSUE THREAD

**Issue by AnnaWegmann** [hayj/DeepStyle#1]
Hi hayj,

Thank you for sharing your code. I am doing some style calculations for documents as well and would like to test out your approach. 

Unfortunately, I can not load your DBert-ft model, i.e., I get an error when running this line:

    m = DeepStyle("DeepStyle/model/212.129.44.40/DeepStyle/dbert-ft/")

First, I get the error 

    NameError: name 'os' is not defined 

    in model.py

When adding the line

   import os 

in DeepStyle/deepstyle/model.py, I get a different error. I tried both, with my current versions (i.e., python 3.8, and some more recent transformers and tensorflow-gpu version) as well as the versions you mentioned (i.e., 2.4.1and 2.0).

In the first case I get the error: 

```
Error
Traceback (most recent call last):
  File "/home/anna/anaconda3/envs/src/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/anna/anaconda3/envs/src/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/anna/anaconda3/envs/src/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/anna/Documents/UU/digital-society_intergenerational-empathy/src/test/test_style_similarity.py", line 27, in test_deepstyle_features
    logging.info(feature_object.deepstyle_features(text))
  File "/home/anna/Documents/UU/digital-society_intergenerational-empathy/src/utility/style_similarity.py", line 91, in deepstyle_features
    model = DeepStyle(model_file)
  File "/home/anna/anaconda3/envs/src/lib/python3.8/site-packages/deepstyle-0.0.1-py3.8.egg/deepstyle/model.py", line 129, in __init__
    self.__load()
  File "/home/anna/anaconda3/envs/src/lib/python3.8/site-packages/deepstyle-0.0.1-py3.8.egg/deepstyle/model.py", line 133, in __load
    self.model = TFDistilBertForSequenceClassification.from_pretrained\
  File "/home/anna/anaconda3/envs/src/lib/python3.8/site-packages/transformers/modeling_tf_utils.py", line 710, in from_pretrained
    load_tf_weights(model, resolved_archive_file)
  File "/home/anna/anaconda3/envs/src/lib/python3.8/site-packages/transformers/modeling_tf_utils.py", line 291, in load_tf_weights
    array = np.reshape(saved_weight_value, K.int_shape(symbolic_weight))
  File "<__array_function__ internals>", line 5, in reshape
  File "/home/anna/anaconda3/envs/src/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/anna/anaconda3/envs/src/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 921600 into shape (768,2)
```

and in the second:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anna/anaconda3/envs/test3.6/lib/python3.6/site-packages/deepstyle-0.0.1-py3.6.egg/deepstyle/model.py", line 129, in __init__
  File "/home/anna/anaconda3/envs/test3.6/lib/python3.6/site-packages/deepstyle-0.0.1-py3.6.egg/deepstyle/model.py", line 136, in __load
  File "/home/anna/anaconda3/envs/test3.6/lib/python3.6/site-packages/transformers/modeling_tf_utils.py", line 355, in from_pretrained
    model.load_weights(resolved_archive_file, by_name=True)
  File "/home/anna/anaconda3/envs/test3.6/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 181, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/home/anna/anaconda3/envs/test3.6/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 1175, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, self.layers)
  File "/home/anna/anaconda3/envs/test3.6/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 718, in load_weights_from_hdf5_group_by_name
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'
```

For now, I am only testing on a computer with only a CPU. But this should not be an error source, I think.

Did you have this problem before? It would be awesome if you can help me out.

**Comment by AnnaWegmann** [comment]
I now also tried it with a GPU:
```

>>> model = DeepStyle("/hpc/uu_cs_nlpsoc/data/conversations/DeepStyle/212.129.44.40/DeepStyle/dbert-ft")
2020-12-08 17:15:11.909192: W tensorflow/python/util/util.cc:329] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
2020-12-08 17:15:11.954390: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2020-12-08 17:15:11.961220: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2700000000 Hz
2020-12-08 17:15:11.961474: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f488bb1020 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-12-08 17:15:11.961511: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-12-08 17:15:11.961671: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/uu_cs_nlpsoc/awegmann/DeepStyle/deepstyle/model.py", line 129, in __init__
    self.__load()
  File "/home/uu_cs_nlpsoc/awegmann/DeepStyle/deepstyle/model.py", line 133, in __load
    self.model = TFDistilBertForSequenceClassification.from_pretrained\
  File "/hpc/local/CentOS7/uu_cs_nlpsoc/conda/envs/aw_style_similarity/lib/python3.8/site-packages/transformers/modeling_tf_utils.py", line 616, in from_pretrained
    model.load_weights(resolved_archive_file, by_name=True)
  File "/hpc/local/CentOS7/uu_cs_nlpsoc/conda/envs/aw_style_similarity/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 250, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "/hpc/local/CentOS7/uu_cs_nlpsoc/conda/envs/aw_style_similarity/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py", line 1263, in load_weights
    hdf5_format.load_weights_from_hdf5_group_by_name(
  File "/hpc/local/CentOS7/uu_cs_nlpsoc/conda/envs/aw_style_similarity/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 780, in load_weights_from_hdf5_group_by_name
    raise ValueError('Layer #' + str(k) +' (named "' + layer.name +
ValueError: Layer #2 (named "classifier"), weight <tf.Variable 'tf_distil_bert_for_sequence_classification/classifier/kernel:0' shape=(768, 2) dtype=float32, numpy=
array([[-0.00159971, -0.00793274],
       [-0.01530189, -0.00791676],
       [-0.0077662 , -0.02859338],
       ...,
       [-0.03073144,  0.00575919],
       [-0.01332873, -0.02662781],
       [ 0.01318847, -0.01922753]], dtype=float32)> has shape (768, 2), but the saved weight has shape (768, 1200).
```

**Comment by salhasalman** [comment]
Hi 
@AnnaWegmann I got the same error.os is not defined.It didnt work even after importing os.

**Comment by AnnaWegmann** [comment]
Hi, 

I could solve this with some help:

add import os  
downgrading h5py to 2.10.0   
2.4.1and 2.0 for transformers and tensorflow-gpu

**Comment by hayj** [comment]
Thank you @AnnaWegmann, I added the `import os` line

I also added a complete command line demo that install right versions of each lib:

```bash
cd ~/tmp
mkdir dbert-ft
cd dbert-ft
wget http://212.129.44.40/DeepStyle/dbert-ft/config.json
wget http://212.129.44.40/DeepStyle/dbert-ft/tf_model.h5
cd ../
conda create -n dbertft-env -y python=3.7 anaconda
conda activate dbertft-env
git clone https://github.com/hayj/deepstyle ; cd deepstyle ; pip uninstall deepstyle -y ; python setup.py install ; cd ../ ; rm -rf deepstyle
pip install --ignore-installed --upgrade tensorflow==2.0.0
pip install --ignore-installed --upgrade transformers==2.4.1
pip install --ignore-installed --upgrade h5py==2.10.0
ipython -c "from deepstyle.model import DeepStyle ; m = DeepStyle('dbert-ft') ; m.embed('Hello World')"
```

**Comment by kunduayan** [comment]
Hi hayj,

The link given [http://212.129.44.40/DeepStyle/dbert-ft/] to download the model and config is not working. 
It would be awesome if you can help me out.

**Comment by hayj** [comment]
Thx, I already noticed it doesn't work. Trying to fix it. In the meantime, pls send me a private msg, I'll give you a temp link.

**Comment by kunduayan** [comment]
Please send the temp link.

Thanks.

**Comment by hayj** [comment]
Here is the link to get the model:
https://drive.google.com/file/d/1Y9TMjj04fVhNuJnhzaM4Wmn2CQfZ8r8U/view?usp=share_link

**Comment by Bornlex** [comment]
Hello guys, thank you for this work!
I also downloaded the model using the link in the README.md file but I get the same error:
```
You passed along `num_labels=1200` with an incompatible id to label map: {'0': 'LABEL_0', '1': 'LABEL_1'}. The number of labels wil be overwritten to 2.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Julien/Documents/Newtone/Admin-UI/scoring/deepstyle/model.py", line 129, in __init__
    self.__load()
  File "/Users/Julien/Documents/Newtone/Admin-UI/scoring/deepstyle/model.py", line 133, in __load
    self.model = TFDistilBertForSequenceClassification.from_pretrained\
  File "/usr/local/lib/python3.9/site-packages/transformers/modeling_tf_utils.py", line 2828, in from_pretrained
    missing_keys, unexpected_keys, mismatched_keys = load_tf_weights(
  File "/usr/local/lib/python3.9/site-packages/transformers/modeling_tf_utils.py", line 889, in load_tf_weights
    return load_function(
  File "/usr/local/lib/python3.9/site-packages/transformers/modeling_tf_utils.py", line 979, in load_tf_weights_from_h5
    raise e
  File "/usr/local/lib/python3.9/site-packages/transformers/modeling_tf_utils.py", line 971, in load_tf_weights_from_h5
    array = np.reshape(saved_weight_value, K.int_shape(symbolic_weight))
  File "<__array_function__ internals>", line 5, in reshape
  File "/usr/local/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 299, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 921600 into shape (768,2)
```

921600 seems to be 768 * 1200.

Is there somewhere else I can get the pretrained model :)?
Thank you for your help.
Kind regards,

**Comment by hayj** [comment]
For me the solution was to execute this ( clone your environment to make sure you keep a backup):

	pip uninstall -y tensorflow && pip install tensorflow==2.0
	pip uninstall -y transformers && pip install transformers==2.4.1
	pip uninstall -y h5py && pip install h5py==2.10.0

**Comment by Bornlex** [comment]
Yes it works!
I got the latest tensorflow version and it works, so I guess it was either transformers or h5py.

Thank you.

**Comment by Bornlex** [comment]
Hey guys,

about the ```ValueError: cannot reshape array of size 921600 into shape (768,2)``` problem. It seems that the configuration file clashes because of the following lines:
```
"id2label": {
  "0": "LABEL_0",
  "1": "LABEL_1"
},
```

I removed them, reinstalled all packages at the latest versions and it loads the model fine :).

Si DeepStyle works with latest packages version which is fine if you need to integrate it inside an existing project as a loss function for instance.

Thanks again for the work.

B.

**Comment by zuoluoyake** [comment]
> 嘿，大家好，
> 
> 关于这个`ValueError: cannot reshape array of size 921600 into shape (768,2)`问题。看来配置文件因为以下几行而发生冲突：
> 
> ```
> "id2label": {
>   "0": "LABEL_0",
>   "1": "LABEL_1"
> },
> ```
> 
> 我删除了它们，重新安装了最新版本的所有软件包，并且可以正常加载模型:)。
> 
> Si DeepStyle 可与最新的软件包版本配合使用，如果您需要将其作为损失函数集成到现有项目中，这很好。
> 
> 再次感谢您的工作。
> 
> B.

太感谢了，哥们！
